UPDATE `sys_dict_data` SET `dict_label` = 'Mạch cắm test (WiFi)', `remark` = 'Mạch cắm test (WiFi)' WHERE `id` = 101001;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch cắm test (WiFi) + LCD', `remark` = 'Mạch cắm test (WiFi) + LCD' WHERE `id` = 101002;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch cắm test (ML307 AT)', `remark` = 'Mạch cắm test (ML307 AT)' WHERE `id` = 101003;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch cắm test (WiFi) ESP32 DevKit', `remark` = 'Mạch cắm test (WiFi) ESP32 DevKit' WHERE `id` = 101004;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch cắm test (WiFi + LCD) ESP32 DevKit', `remark` = 'Mạch cắm test (WiFi + LCD) ESP32 DevKit' WHERE `id` = 101005;
UPDATE `sys_dict_data` SET `dict_label` = 'DFRobot UNIHIKER K10', `remark` = 'DFRobot UNIHIKER K10' WHERE `id` = 101006;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch phát triển Kevin SP V3', `remark` = 'Mạch phát triển Kevin SP V3' WHERE `id` = 101014;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch phát triển Kevin SP V4', `remark` = 'Mạch phát triển Kevin SP V4' WHERE `id` = 101015;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch Yuying 3.13LCD', `remark` = 'Mạch Yuying 3.13LCD' WHERE `id` = 101016;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch Lichuang ESP32-S3', `remark` = 'Mạch Lichuang ESP32-S3' WHERE `id` = 101017;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch Lichuang ESP32-C3', `remark` = 'Mạch Lichuang ESP32-C3' WHERE `id` = 101018;
UPDATE `sys_dict_data` SET `dict_label` = 'Nút bấm Magiclick 2.4', `remark` = 'Nút bấm Magiclick 2.4' WHERE `id` = 101019;
UPDATE `sys_dict_data` SET `dict_label` = 'Nút bấm Magiclick 2.5', `remark` = 'Nút bấm Magiclick 2.5' WHERE `id` = 101020;
UPDATE `sys_dict_data` SET `dict_label` = 'Nút bấm Magiclick C3', `remark` = 'Nút bấm Magiclick C3' WHERE `id` = 101021;
UPDATE `sys_dict_data` SET `dict_label` = 'Nút bấm Magiclick C3 v2', `remark` = 'Nút bấm Magiclick C3 v2' WHERE `id` = 101022;
UPDATE `sys_dict_data` SET `dict_label` = 'Xiage Mini C3', `remark` = 'Xiage Mini C3' WHERE `id` = 101028;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch phát triển ESP32S3 KORVO2 V3', `remark` = 'Mạch phát triển ESP32S3 KORVO2 V3' WHERE `id` = 101029;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch phát triển ESP-SparkBot', `remark` = 'Mạch phát triển ESP-SparkBot' WHERE `id` = 101030;
UPDATE `sys_dict_data` SET `dict_label` = 'Tudouzi', `remark` = 'Tudouzi' WHERE `id` = 101037;
UPDATE `sys_dict_data` SET `dict_label` = 'Movecall Moji Xiaozhi AI', `remark` = 'Movecall Moji Xiaozhi AI' WHERE `id` = 101040;
UPDATE `sys_dict_data` SET `dict_label` = 'Movecall CuiCan Mặt dây chuyền AI', `remark` = 'Movecall CuiCan Mặt dây chuyền AI' WHERE `id` = 101041;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch phát triển ATK DNESP32S3', `remark` = 'Mạch phát triển ATK DNESP32S3' WHERE `id` = 101042;
UPDATE `sys_dict_data` SET `dict_label` = 'ATK DNESP32S3-BOX', `remark` = 'ATK DNESP32S3-BOX' WHERE `id` = 101043;
UPDATE `sys_dict_data` SET `dict_label` = 'Mạch Dudu CHATX (WiFi)', `remark` = 'Mạch Dudu CHATX (WiFi)' WHERE `id` = 101044;
UPDATE `sys_dict_data` SET `dict_label` = 'Taiji Pi ESP32-S3', `remark` = 'Taiji Pi ESP32-S3' WHERE `id` = 101045;
UPDATE `sys_dict_data` SET `dict_label` = 'Xingzhi 0.85 (WiFi)', `remark` = 'Xingzhi 0.85 (WiFi)' WHERE `id` = 101046;
UPDATE `sys_dict_data` SET `dict_label` = 'Xingzhi 0.85 (ML307)', `remark` = 'Xingzhi 0.85 (ML307)' WHERE `id` = 101047;
UPDATE `sys_dict_data` SET `dict_label` = 'Xingzhi 0.96 (WiFi)', `remark` = 'Xingzhi 0.96 (WiFi)' WHERE `id` = 101048;
UPDATE `sys_dict_data` SET `dict_label` = 'Xingzhi 0.96 (ML307)', `remark` = 'Xingzhi 0.96 (ML307)' WHERE `id` = 101049;
UPDATE `sys_dict_data` SET `dict_label` = 'Xingzhi 1.54 (WiFi)', `remark` = 'Xingzhi 1.54 (WiFi)' WHERE `id` = 101050;
UPDATE `sys_dict_data` SET `dict_label` = 'Xingzhi 1.54 (ML307)', `remark` = 'Xingzhi 1.54 (ML307)' WHERE `id` = 101051;
UPDATE `sys_dict_data` SET `dict_label` = 'Hộp AI Doit S3', `remark` = 'Hộp AI Doit S3' WHERE `id` = 101053;
UPDATE `sys_dict_data` SET `dict_label` = 'Mixgo Nova', `remark` = 'Mixgo Nova' WHERE `id` = 101054;
